{
  "sksl": {
    "entrypoint": "blur_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float time;\nuniform vec2 size;\nuniform float strength;\n\nvec4 FragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 texcoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv = texcoord / size;\n    float modifier = 0.100000001490116119384765625;\n    float noise = fract(sin(dot(uv, vec2(12.98980045318603515625 * time, 78.233001708984375 * time))) * 43758.54296875);\n    modifier *= (0.564642488956451416015625 + strength);\n    vec4 col = vec4(1.0) - vec4(noise * modifier);\n    FragColor = vec4(1.0, 0.0, 0.0, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return FragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "time",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "size",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "strength",
        "rows": 1,
        "type": 10
      }
    ]
  }
}